// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using OraclePrimavera.Data;

#nullable disable

namespace OraclePrimavera.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OraclePrimavera.Data.ProjectRecord", b =>
                {
                    b.Property<int>("ProctorNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProctorNo"));

                    b.Property<decimal?>("ActualCostAmount")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal?>("AnticipatedCost")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("AttachUrl")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Attachment")
                        .HasColumnType("CLOB");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("ContractNo")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("CostCode")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Currency")
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("NCLOB");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("ProjectEndDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("ProjectOHName")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<DateTime?>("ProjectStartDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("RecordNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("ProctorNo");

                    b.ToTable("ProjectRecords");
                });

            modelBuilder.Entity("OraclePrimavera.Data.ProjectRecordFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Base64File")
                        .HasColumnType("CLOB");

                    b.Property<string>("Extension")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("FileName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("FileUrl")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MimeType")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<long>("ProjectRecordId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("Size")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.ToTable("ProjectRecordFile");
                });

            modelBuilder.Entity("OraclePrimavera.Data.ProjectRecordManual", b =>
                {
                    b.Property<int>("ProctorNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProctorNo"));

                    b.Property<decimal?>("ActualCostAmount")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal?>("AnticipatedCost")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("AttachUrl")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Attachment")
                        .HasColumnType("CLOB");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("ContractNo")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("CostCode")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Currency")
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("NCLOB");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("ProjectEndDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("ProjectOHName")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<DateTime?>("ProjectStartDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("RecordNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("ProctorNo");

                    b.ToTable("ProjectRecordManual");
                });
#pragma warning restore 612, 618
        }
    }
}
